### ISSUE TITLE
Data Error (cyclic redundancy check) when dumping certain games

### ISSUE THREAD

**Issue by ProtoProxi** [13xforever/ps3-disc-dumper#51]
Hello friends, 
In my efforts to dump my copy of Ratchet and Clank Future: Tools of Destruction (BCUS-98127), I am met with the following error after a longer than usual wait than other games I was able to dump. I just wanted to poll around before I resign to getting another copy. Most of the open source research I performed had me run chkdsk, but it's kind of hard to run that on a blu ray burner. Let me know what else you need from me to help document this if needed. Thank you. 

The log is abbreviated after another unsuccessful dump of the same title. It was a 22-ish GB file, before, so lots of guff removed. Still displays the same error I am currently diagnosing.

Log below:

2024-01-01 01:12:29	598	INFO	PS3 Disc Dumper v4.0.7
2024-01-01 01:12:38	10364	INFO	Selected disc: D:\
2024-01-01 01:12:44	15691	DEBUG	Disc flags: gu
2024-01-01 01:12:44	15692	DEBUG	Disc product code: BCUS-98127
2024-01-01 01:12:56	28327	INFO	Game title: Ratchet and Clank® Future: Tools of Destruction™
2024-01-01 01:12:56	28327	INFO	Game product code: BCUS98127
2024-01-01 01:12:56	28328	INFO	Game version: 01.00
2024-01-01 01:12:56	28328	INFO	App version: 01.00
2024-01-01 01:16:53	13	INFO	Loading settings…
2024-01-01 01:16:53	21	INFO	Current settings: {
  "OutputDir": "G:\\ROM Rip Holding",
  "IrdDir": "C:\\Users\\a\\Desktop\\ps3-disc-dumper_windows_v4.0.7\\Key Info\\Sony - PlayStation 3 - Disc Keys (4289) (2023-12-29 12-49-43)",
  "DumpNameTemplate": "%title% [%product_code%]",
  "ShowDetails": true,
  "EnableTransparency": true,
  "PreferSystemAccent": true,
  "StayOnTop": true
}
2024-01-01 01:16:54	631	INFO	PS3 Disc Dumper v4.0.7
2024-01-01 01:16:54	687	INFO	Selected disc: D:\
2024-01-01 01:16:54	747	DEBUG	Disc flags: gu
2024-01-01 01:16:54	747	DEBUG	Disc product code: BCUS-98127
2024-01-01 01:16:54	753	INFO	Game title: Ratchet and Clank® Future: Tools of Destruction™
2024-01-01 01:16:54	753	INFO	Game product code: BCUS98127
2024-01-01 01:16:54	753	INFO	Game version: 01.00
2024-01-01 01:16:54	753	INFO	App version: 01.00
2024-01-01 01:16:56	2496	DEBUG	Dump folder name: Ratchet and Clank Future_ Tools of Destruction [BCUS98127]
2024-01-01 01:16:56	2505	TRACE	Getting keys from IrdProvider...
2024-01-01 01:16:56	2507	TRACE	Searching local cache for a match...
2024-01-01 01:16:56	2514	TRACE	Searching for IRDs using 2 sources for a match...
2024-01-01 01:16:58	4627	INFO	Found 4 new IRD matches
2024-01-01 01:16:58	4627	DEBUG	Trying to download 5559EE3F_D476BE7C_26F35636_5C6B541D.ird from ps3ird.free.fr...
2024-01-01 01:16:58	5130	DEBUG	Trying to download 6CD4D2FA_F4ECD701_E99977E0_2F3163CF.ird from ps3ird.free.fr...
2024-01-01 01:16:59	5624	DEBUG	Trying to download BCUS98127-2617743B687C69972FB10DF0955F1F45.ird from ps3.aldostools.org...
2024-01-01 01:16:59	5715	DEBUG	Trying to download BCUS98127-DE31BE655EE13254551E105F1A44480D.ird from ps3.aldostools.org...
2024-01-01 01:16:59	5805	INFO	Found 3 IRD files
2024-01-01 01:16:59	5805	TRACE	Got 3 keys from IrdProvider
2024-01-01 01:16:59	5806	TRACE	Getting keys from RedumpProvider...
2024-01-01 01:17:01	7424	INFO	Latest redump snapshot: Sony - PlayStation 3 - Disc Keys (4289) (2023-12-29 12-49-43).zip
2024-01-01 01:17:01	7425	INFO	Saving latest redump snapshot in local cache: Sony - PlayStation 3 - Disc Keys (4289) (2023-12-29 12-49-43).zip...
2024-01-01 01:17:01	7426	INFO	Using locally cached redump keys snapshot
2024-01-01 01:17:01	7472	INFO	Found 4105 redump keys
2024-01-01 01:17:01	7472	TRACE	Loading loose cached redump keys
2024-01-01 01:17:01	7472	INFO	Found 0 cached disc keys
2024-01-01 01:17:01	7472	TRACE	Got 4105 keys from RedumpProvider
2024-01-01 01:17:01	7474	TRACE	Trying to enumerate physical drives...
2024-01-01 01:17:08	15103	INFO	Found optical media drive HL-DT-ST BD-RE  WH14NS40 (D:)
2024-01-01 01:17:08	15103	DEBUG	Found 1 physical drives
2024-01-01 01:17:08	15103	TRACE	Checking physical drive \\.\CDROM0...
2024-01-01 01:17:09	15322	TRACE	Found PS3_DISC.SFB, getting sector data...
2024-01-01 01:17:09	15324	TRACE	PS3_DISC.SFB sector number is 2048, reading content...
2024-01-01 01:17:11	17337	DEBUG	Skipping drive \\.\CDROM0: Data error (cyclic redundancy check). : '\\.\CDROM0'
2024-01-01 01:17:11	17337	ERROR	Failed to find a matching key
System.AccessViolationException: Direct disk access to the drive was denied
   at Ps3DiscDumper.Dumper.FindDiscKeyAsync(String discKeyCachePath)
   at UI.Avalonia.ViewModels.MainViewModel.ScanDiscsAsync()
2024-01-01 01:17:35	42014	INFO	Selected disc: D:\
2024-01-01 01:17:35	42086	DEBUG	Disc flags: gu
2024-01-01 01:17:35	42086	DEBUG	Disc product code: BCUS-98127
2024-01-01 01:17:36	42228	INFO	Game title: Ratchet and Clank® Future: Tools of Destruction™
2024-01-01 01:17:36	42228	INFO	Game product code: BCUS98127
2024-01-01 01:17:36	42228	INFO	Game version: 01.00
2024-01-01 01:17:36	42228	INFO	App version: 01.00
2024-01-01 01:17:49	55269	DEBUG	Dump folder name: Ratchet and Clank Future_ Tools of Destruction [BCUS98127]
2024-01-01 01:17:49	55270	TRACE	Getting keys from IrdProvider...
2024-01-01 01:17:49	55270	TRACE	Searching local cache for a match...
2024-01-01 01:17:49	55275	TRACE	Searching for IRDs using 2 sources for a match...
2024-01-01 01:17:51	57292	DEBUG	No matching IRD file was found at any source
2024-01-01 01:17:51	57292	INFO	Found 3 IRD files
2024-01-01 01:17:51	57292	TRACE	Got 3 keys from IrdProvider
2024-01-01 01:17:51	57292	TRACE	Getting keys from RedumpProvider...
2024-01-01 01:17:51	57292	INFO	Using locally cached redump keys snapshot
2024-01-01 01:17:51	57313	INFO	Found 4105 redump keys
2024-01-01 01:17:51	57314	TRACE	Loading loose cached redump keys
2024-01-01 01:17:51	57314	INFO	Found 0 cached disc keys
2024-01-01 01:17:51	57314	TRACE	Got 4105 keys from RedumpProvider
2024-01-01 01:17:51	57315	TRACE	Trying to enumerate physical drives...
2024-01-01 01:17:56	62682	INFO	Found optical media drive HL-DT-ST BD-RE  WH14NS40 (D:)
2024-01-01 01:17:56	62682	DEBUG	Found 1 physical drives
2024-01-01 01:17:56	62682	TRACE	Checking physical drive \\.\CDROM0...
2024-01-01 01:17:56	62767	TRACE	Found PS3_DISC.SFB, getting sector data...
2024-01-01 01:17:56	62767	TRACE	PS3_DISC.SFB sector number is 2048, reading content...
2024-01-01 01:17:56	62809	DEBUG	Selected physical drive \\.\CDROM0
2024-01-01 01:17:56	62894	DEBUG	Using \PS3_GAME\USRDIR\EBOOT.BIN for disc key detection
2024-01-01 01:17:56	62894	DEBUG	Initialized sectorIV (128 bit) for sector 4032: 00000000000000000000000000000fc0
2024-01-01 01:17:56	62958	INFO	Selected disc key: 102446ea137cdad84fdd64ef022ac4fc, known key sources:
2024-01-01 01:17:56	62959	DEBUG		Ird: 5559EE3F_D476BE7C_26F35636_5C6B541D.ird
2024-01-01 01:17:56	62959	DEBUG		Ird: 6CD4D2FA_F4ECD701_E99977E0_2F3163CF.ird
2024-01-01 01:17:56	62959	DEBUG		Ird: BCUS98127-DE31BE655EE13254551E105F1A44480D.ird
2024-01-01 01:17:56	62959	DEBUG		Redump: Ratchet & Clank Future - Tools of Destruction (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi,Zh,Ko) (v01.00).key
2024-01-01 01:18:11	77596	ERROR	Failed to dump the disc
System.IO.IOException: Data error (cyclic redundancy check). : '\\.\CDROM0'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle handle, Span`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ps3DiscDumper.Utils.StreamEx.ReadExact(Stream input, Byte[] buffer, Int32 offset, Int32 count)
   at Ps3DiscDumper.Dumper.GetFilesystemStructure()
   at Ps3DiscDumper.Dumper.DumpAsync(String output)
   at UI.Avalonia.ViewModels.MainViewModel.DumpDiscAsync()
2024-01-01 01:23:47	413647	INFO	Selected disc: D:\
2024-01-01 01:23:47	413649	DEBUG	Disc flags: gu
2024-01-01 01:23:47	413649	DEBUG	Disc product code: BCUS-98127
2024-01-01 01:23:47	413652	INFO	Game title: Ratchet and Clank® Future: Tools of Destruction™
2024-01-01 01:23:47	413652	INFO	Game product code: BCUS98127
2024-01-01 01:23:47	413652	INFO	Game version: 01.00
2024-01-01 01:23:47	413652	INFO	App version: 01.00
2024-01-01 01:23:49	415661	DEBUG	Dump folder name: Ratchet and Clank Future_ Tools of Destruction [BCUS98127]
2024-01-01 01:23:49	415662	TRACE	Getting keys from IrdProvider...
2024-01-01 01:23:49	415662	TRACE	Searching local cache for a match...
2024-01-01 01:23:49	415671	TRACE	Searching for IRDs using 2 sources for a match...
2024-01-01 01:23:51	417754	DEBUG	No matching IRD file was found at any source
2024-01-01 01:23:51	417754	INFO	Found 3 IRD files
2024-01-01 01:23:51	417754	TRACE	Got 3 keys from IrdProvider
2024-01-01 01:23:51	417754	TRACE	Getting keys from RedumpProvider...
2024-01-01 01:23:51	417754	INFO	Using locally cached redump keys snapshot
2024-01-01 01:23:51	417781	INFO	Found 4105 redump keys
2024-01-01 01:23:51	417781	TRACE	Loading loose cached redump keys
2024-01-01 01:23:51	417781	INFO	Found 0 cached disc keys
2024-01-01 01:23:51	417781	TRACE	Got 4105 keys from RedumpProvider
2024-01-01 01:23:51	417791	TRACE	Trying to enumerate physical drives...
2024-01-01 01:24:04	430285	INFO	Found optical media drive HL-DT-ST BD-RE  WH14NS40 (D:)
2024-01-01 01:24:04	430285	DEBUG	Found 1 physical drives
2024-01-01 01:24:04	430285	TRACE	Checking physical drive \\.\CDROM0...
2024-01-01 01:24:10	436275	DEBUG	Skipping drive \\.\CDROM0: Data error (cyclic redundancy check). : '\\.\CDROM0'
2024-01-01 01:24:10	436275	ERROR	Failed to find a matching key
System.AccessViolationException: Direct disk access to the drive was denied
   at Ps3DiscDumper.Dumper.FindDiscKeyAsync(String discKeyCachePath)
   at UI.Avalonia.ViewModels.MainViewModel.ScanDiscsAsync()
2024-01-01 01:24:30	456738	INFO	Selected disc: D:\
2024-01-01 01:24:30	456743	DEBUG	Disc flags: gu
2024-01-01 01:24:30	456743	DEBUG	Disc product code: BCUS-98127
2024-01-01 01:24:30	456753	INFO	Game title: Ratchet and Clank® Future: Tools of Destruction™
2024-01-01 01:24:30	456753	INFO	Game product code: BCUS98127
2024-01-01 01:24:30	456753	INFO	Game version: 01.00
2024-01-01 01:24:30	456753	INFO	App version: 01.00
2024-01-01 01:24:31	457255	DEBUG	Dump folder name: Ratchet and Clank Future_ Tools of Destruction [BCUS98127]
2024-01-01 01:24:31	457255	TRACE	Getting keys from IrdProvider...
2024-01-01 01:24:31	457255	TRACE	Searching local cache for a match...
2024-01-01 01:24:31	457258	TRACE	Searching for IRDs using 2 sources for a match...
2024-01-01 01:24:33	459360	DEBUG	No matching IRD file was found at any source
2024-01-01 01:24:33	459360	INFO	Found 3 IRD files
2024-01-01 01:24:33	459360	TRACE	Got 3 keys from IrdProvider
2024-01-01 01:24:33	459360	TRACE	Getting keys from RedumpProvider...
2024-01-01 01:24:33	459360	INFO	Using locally cached redump keys snapshot
2024-01-01 01:24:33	459377	INFO	Found 4105 redump keys
2024-01-01 01:24:33	459377	TRACE	Loading loose cached redump keys
2024-01-01 01:24:33	459377	INFO	Found 0 cached disc keys
2024-01-01 01:24:33	459377	TRACE	Got 4105 keys from RedumpProvider
2024-01-01 01:24:33	459378	TRACE	Trying to enumerate physical drives...
2024-01-01 01:24:41	467332	INFO	Found optical media drive HL-DT-ST BD-RE  WH14NS40 (D:)
2024-01-01 01:24:41	467332	DEBUG	Found 1 physical drives
2024-01-01 01:24:41	467332	TRACE	Checking physical drive \\.\CDROM0...
2024-01-01 01:24:45	472201	DEBUG	Skipping drive \\.\CDROM0: Data error (cyclic redundancy check). : '\\.\CDROM0'
2024-01-01 01:24:45	472201	ERROR	Failed to find a matching key
System.AccessViolationException: Direct disk access to the drive was denied
   at Ps3DiscDumper.Dumper.FindDiscKeyAsync(String discKeyCachePath)
   at UI.Avalonia.ViewModels.MainViewModel.ScanDiscsAsync()
2024-01-01 01:24:57	9	INFO	Loading settings…
2024-01-01 01:24:57	11	INFO	Current settings: {
  "OutputDir": "G:\\ROM Rip Holding",
  "IrdDir": "C:\\Users\\a\\Desktop\\ps3-disc-dumper_windows_v4.0.7\\Key Info\\Sony - PlayStation 3 - Disc Keys (4289) (2023-12-29 12-49-43)",
  "DumpNameTemplate": "%title% [%product_code%]",
  "ShowDetails": true,
  "EnableTransparency": true,
  "PreferSystemAccent": true,
  "StayOnTop": true
}
2024-01-01 01:24:57	536	INFO	PS3 Disc Dumper v4.0.7
2024-01-01 01:24:57	573	INFO	Selected disc: D:\
2024-01-01 01:24:57	575	DEBUG	Disc flags: gu
2024-01-01 01:24:57	575	DEBUG	Disc product code: BCUS-98127
2024-01-01 01:24:57	577	INFO	Game title: Ratchet and Clank® Future: Tools of Destruction™
2024-01-01 01:24:57	577	INFO	Game product code: BCUS98127
2024-01-01 01:24:57	577	INFO	Game version: 01.00
2024-01-01 01:24:57	577	INFO	App version: 01.00
2024-01-01 01:24:58	1033	DEBUG	Dump folder name: Ratchet and Clank Future_ Tools of Destruction [BCUS98127]
2024-01-01 01:24:58	1041	TRACE	Getting keys from IrdProvider...
2024-01-01 01:24:58	1042	TRACE	Searching local cache for a match...
2024-01-01 01:24:58	1061	TRACE	Searching for IRDs using 2 sources for a match...
2024-01-01 01:25:00	3227	DEBUG	No matching IRD file was found at any source
2024-01-01 01:25:00	3227	INFO	Found 3 IRD files
2024-01-01 01:25:00	3227	TRACE	Got 3 keys from IrdProvider
2024-01-01 01:25:00	3227	TRACE	Getting keys from RedumpProvider...
2024-01-01 01:25:01	4685	INFO	Latest redump snapshot: Sony - PlayStation 3 - Disc Keys (4289) (2023-12-29 12-49-43).zip
2024-01-01 01:25:01	4686	INFO	Using local copy of redump key snapshot
2024-01-01 01:25:01	4688	INFO	Using locally cached redump keys snapshot
2024-01-01 01:25:01	4723	INFO	Found 4105 redump keys
2024-01-01 01:25:01	4723	TRACE	Loading loose cached redump keys
2024-01-01 01:25:01	4724	INFO	Found 0 cached disc keys
2024-01-01 01:25:01	4724	TRACE	Got 4105 keys from RedumpProvider
2024-01-01 01:25:01	4725	TRACE	Trying to enumerate physical drives...
2024-01-01 01:25:11	14042	INFO	Found optical media drive HL-DT-ST BD-RE  WH14NS40 (D:)
2024-01-01 01:25:11	14042	DEBUG	Found 1 physical drives
2024-01-01 01:25:11	14042	TRACE	Checking physical drive \\.\CDROM0...
2024-01-01 01:25:17	20362	DEBUG	Skipping drive \\.\CDROM0: Data error (cyclic redundancy check). : '\\.\CDROM0'
2024-01-01 01:25:17	20363	ERROR	Failed to find a matching key
System.AccessViolationException: Direct disk access to the drive was denied
   at Ps3DiscDumper.Dumper.FindDiscKeyAsync(String discKeyCachePath)
   at UI.Avalonia.ViewModels.MainViewModel.ScanDiscsAsync()
2024-01-01 01:26:26	9	INFO	Loading settings…
2024-01-01 01:26:26	12	INFO	Current settings: {
  "OutputDir": "G:\\ROM Rip Holding",
  "IrdDir": "C:\\Users\\a\\Desktop\\ps3-disc-dumper_windows_v4.0.7\\Key Info\\Sony - PlayStation 3 - Disc Keys (4289) (2023-12-29 12-49-43)",
  "DumpNameTemplate": "%title% [%product_code%]",
  "ShowDetails": true,
  "EnableTransparency": true,
  "PreferSystemAccent": true,
  "StayOnTop": true
}
2024-01-01 01:26:26	552	INFO	PS3 Disc Dumper v4.0.7
2024-01-01 01:26:42	16587	INFO	Selected disc: D:\
2024-01-01 01:26:43	16634	DEBUG	Disc flags: gu
2024-01-01 01:26:43	16634	DEBUG	Disc product code: BCUS-98127
2024-01-01 01:26:43	16776	INFO	Game title: Ratchet and Clank® Future: Tools of Destruction™
2024-01-01 01:26:43	16776	INFO	Game product code: BCUS98127
2024-01-01 01:26:43	16776	INFO	Game version: 01.00
2024-01-01 01:26:43	16776	INFO	App version: 01.00
2024-01-01 01:26:49	23122	DEBUG	Dump folder name: Ratchet and Clank Future_ Tools of Destruction [BCUS98127]
2024-01-01 01:26:49	23129	TRACE	Getting keys from IrdProvider...
2024-01-01 01:26:49	23130	TRACE	Searching local cache for a match...
2024-01-01 01:26:49	23152	TRACE	Searching for IRDs using 2 sources for a match...
2024-01-01 01:26:51	25195	DEBUG	No matching IRD file was found at any source
2024-01-01 01:26:51	25195	INFO	Found 3 IRD files
2024-01-01 01:26:51	25195	TRACE	Got 3 keys from IrdProvider
2024-01-01 01:26:51	25195	TRACE	Getting keys from RedumpProvider...
2024-01-01 01:26:53	26684	INFO	Latest redump snapshot: Sony - PlayStation 3 - Disc Keys (4289) (2023-12-29 12-49-43).zip
2024-01-01 01:26:53	26684	INFO	Using local copy of redump key snapshot
2024-01-01 01:26:53	26685	INFO	Using locally cached redump keys snapshot
2024-01-01 01:26:53	26719	INFO	Found 4105 redump keys
2024-01-01 01:26:53	26719	TRACE	Loading loose cached redump keys
2024-01-01 01:26:53	26720	INFO	Found 0 cached disc keys
2024-01-01 01:26:53	26720	TRACE	Got 4105 keys from RedumpProvider
2024-01-01 01:26:53	26721	TRACE	Trying to enumerate physical drives...
2024-01-01 01:26:57	31403	INFO	Found optical media drive HL-DT-ST BD-RE  WH14NS40 (D:)
2024-01-01 01:26:57	31403	DEBUG	Found 1 physical drives
2024-01-01 01:26:57	31403	TRACE	Checking physical drive \\.\CDROM0...
2024-01-01 01:26:57	31474	TRACE	Found PS3_DISC.SFB, getting sector data...
2024-01-01 01:26:57	31476	TRACE	PS3_DISC.SFB sector number is 2048, reading content...
2024-01-01 01:26:57	31501	DEBUG	Selected physical drive \\.\CDROM0
2024-01-01 01:26:57	31571	DEBUG	Using \PS3_GAME\USRDIR\EBOOT.BIN for disc key detection
2024-01-01 01:26:57	31571	DEBUG	Initialized sectorIV (128 bit) for sector 4032: 00000000000000000000000000000fc0
2024-01-01 01:26:58	31611	INFO	Selected disc key: 102446ea137cdad84fdd64ef022ac4fc, known key sources:
2024-01-01 01:26:58	31611	DEBUG		Ird: 5559EE3F_D476BE7C_26F35636_5C6B541D.ird
2024-01-01 01:26:58	31611	DEBUG		Ird: 6CD4D2FA_F4ECD701_E99977E0_2F3163CF.ird
2024-01-01 01:26:58	31611	DEBUG		Ird: BCUS98127-DE31BE655EE13254551E105F1A44480D.ird
2024-01-01 01:26:58	31611	DEBUG		Redump: Ratchet & Clank Future - Tools of Destruction (USA) (En,Ja,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi,Zh,Ko) (v01.00).key
2024-01-01 01:27:06	39873	ERROR	Failed to dump the disc
System.IO.IOException: Data error (cyclic redundancy check). : '\\.\CDROM0'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle handle, Span`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Ps3DiscDumper.Utils.StreamEx.ReadExact(Stream input, Byte[] buffer, Int32 offset, Int32 count)
   at Ps3DiscDumper.Dumper.GetFilesystemStructure()
   at Ps3DiscDumper.Dumper.DumpAsync(String output)
   at UI.Avalonia.ViewModels.MainViewModel.DumpDiscAsync()

**Comment by 13xforever** [comment]
It just means your blu-ray drive couldn't read the sector (dirty/damaged disc, dirty/damaged odd head, etc)

**Comment by ProtoProxi** [comment]
That's kind of what I was leaning toward. Nice to get an opinion straight from the source. I'll probably report back with another attempt with another copy of the game. You do some good work!
