### ISSUE TITLE
Linux build: stuck on initial start-ui

### ISSUE THREAD

**Issue by copra858** [13xforever/ps3-disc-dumper#54]
When opening the ps3-disc-dumper, I see the start UI telling me: "Please insert a PS3 game disc" and there is the button "rescan disc devices". 

Nothing else is happening. I have already PS3 disc inside. Clicking on the rescan-button also does not do anything.

My computer:
- OS: Linux Mint 21.2 Cinnamon
- Kernel: 6.5.0-14-generic

I found this log file, maybe this helps figuring out what the issue is?

```
2024-01-26 09:22:20	18	INFO	Loading settings…
2024-01-26 09:22:20	23	INFO	Current settings: {
  "OutputDir": ".",
  "IrdDir": "/home/copra/Downloads",
  "DumpNameTemplate": "%title% [%product_code%]",
  "ShowDetails": true,
  "EnableTransparency": true,
  "PreferSystemAccent": false,
  "StayOnTop": false
}
2024-01-26 09:22:21	802	ERROR	Failed to open dmesg
System.IO.IOException: Invalid argument : '/dev/kmsg'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle handle, Span`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at UI.Avalonia.Views.MainWindow.MonitorDmesg()
2024-01-26 09:22:21	937	INFO	PS3 Disc Dumper v4.1.0
```

any idea?

**Comment by 13xforever** [comment]
your disc drive can't read ps3 discs ¯\_(ツ)_/¯
